#Development Configuration
WEBSVC_URL_DEV:                        'https://cafexwstest.careerbuilder.com/CAFinancialExternalWS'
assertion_consumer_service_url_dev:    'http://ec2-23-21-129-107.compute-1.amazonaws.com/saml/consume'
issuer_dev:                            'http://ec2-23-21-129-107.compute-1.amazonaws.com/' # the name of your application
idp_sso_target_url_dev:                'https://cbtest.okta.com/app/template_saml_2_0/k4aberjrODWHGWIYFSXI/sso/saml'
idp_cert_fingerprint_dev:              '02:05:79:D8:96:CC:CA:54:2F:16:E2:6E:7D:32:F3:54:95:61:89:71'

#Production Configuration
WEBSVC_URL_PROD:                   'https://cafinexws.careerbuilder.com/CAFinancialExternalWS'
#assertion_consumer_service_url:    'http://ec2-54-227-248-218.compute-1.amazonaws.com/saml/consume'
#issuer:                            'http://ec2-54-227-248-218.compute-1.amazonaws.com/' # the name of your application
#idp_sso_target_url:                'https://cbtest.okta.com/app/template_saml_2_0/k4aberjrODWHGWIYFSXI/sso/saml'
#idp_cert_fingerprint:              '02:05:79:D8:96:CC:CA:54:2F:16:E2:6E:7D:32:F3:54:95:61:89:71'
assertion_consumer_service_url:    'http://localhost:3000/saml/consume'
issuer:                            'http://localhost:3000/' # the name of your application
idp_sso_target_url:                'https://cbtest.okta.com/app/template_saml_2_0/k4aberjrODWHGWIYFSXI/sso/saml'
idp_cert_fingerprint:              '02:05:79:D8:96:CC:CA:54:2F:16:E2:6E:7D:32:F3:54:95:61:89:71'


