#Development Configuration
WEBSVC_URL_DEV: 'https://cafexwstest.careerbuilder.com/CAFinancialExternalWS'

#Production Configuration
WEBSVC_URL_PROD: 'https://cafinexws.careerbuilder.com/CAFinancialExternalWS'


